[package]
name = "BFScriptV2"
version = "0.1.0"
authors = ["RecursiveDescent"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
